#!/bin/bash

set -e

modified_packages=$(./scripts/sync-package-specs)

if [ -n "$modified_packages" ]; then
  echo $'\e[31mthe following package specs are not staged:\e[0m'
  echo
  echo "$modified_packages"
  exit 1
fi

