#!/bin/sh

# Copied from .git/hooks/pre-push.sample
remote="$1"
url="$2"
branch=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

z40=0000000000000000000000000000000000000000


if [ "$branch" != "develop" ]; then
	exit 0
fi

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi

		# Check for WIP commit
		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
		if [ -n "$commit" ]
		then
			echo >&2 "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done

exit 0
