#!/bin/sh

bad_author="Your Name you@example.com"

commit_has_bad_author() {
    git log "@{upstream}".. --pretty=format:"%an %ae" |
        grep -c "$bad_author" > /dev/null
}

check_for_bad_commits() {
    if commit_has_bad_author;
    then
    cat <<EOF
Error: Attempt to push a commit with bad author config.

Double check your local commits and ensure you have the

correct author information for each commit.

EOF
        exit 1
    fi
}

check_for_bad_commits
