// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package batch_test

type mockDroppedMessageCounter struct {
	DropCalled chan bool
	DropInput  struct {
		Count chan uint32
	}
}

func newMockDroppedMessageCounter() *mockDroppedMessageCounter {
	m := &mockDroppedMessageCounter{}
	m.DropCalled = make(chan bool, 100)
	m.DropInput.Count = make(chan uint32, 100)
	return m
}
func (m *mockDroppedMessageCounter) Drop(count uint32) {
	m.DropCalled <- true
	m.DropInput.Count <- count
}
