version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "v106.x"
    schedule:
      interval: "daily"
    labels:
    - "v106.x"
    - "github_actions"
    - "dependencies"

  # Maintain dependencies for Go Modules
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/src"
    target-branch: "v106.x"
    schedule:
      interval: "daily"
    labels:
    - "v106.x"
    - "go"
    - "dependencies"
