#!/bin/bash

RUN_DIR=/var/vcap/sys/run/metron_agent
LOG_DIR=/var/vcap/store/log
JOB_DIR=/var/vcap/jobs/metron_agent
PACKAGE_DIR=/var/vcap/packages/metron_agent/syslog_daemon_config

BIN_DIR=$JOB_DIR/bin
PIDFILE=$RUN_DIR/syslog_daemon_config.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)

    pid_guard $PIDFILE "Syslog Daemon"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    rm -f /etc/cron.daily/bzip_old_logs
    cp -a $BIN_DIR/gzip_old_logs /etc/cron.daily
    cp -a $BIN_DIR/reap_old_logs /etc/cron.hourly
    cp -a $BIN_DIR/symlink_logs /etc/cron.hourly
    cp -a $PACKAGE_DIR/send_error_mail /etc/cron.daily

    exec rsyslogd -f $JOB_DIR/config/rsyslogd.conf -i $PIDFILE -c 4 -x

    ;;

  stop)
    kill_and_wait $PIDFILE
    rm /etc/cron.daily/gzip_old_logs
    rm /etc/cron.hourly/reap_old_logs

    ;;

  *)
    echo "Usage: syslog_daemon_config_ctl {start|stop}"

    ;;

esac
