// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package eventmarshaller_test

type mockByteWriter struct {
	WriteCalled chan bool
	WriteInput  struct {
		Message chan []byte
	}
	WriteOutput struct {
		SentLength chan int
		Err        chan error
	}
}

func newMockByteWriter() *mockByteWriter {
	m := &mockByteWriter{}
	m.WriteCalled = make(chan bool, 100)
	m.WriteInput.Message = make(chan []byte, 100)
	m.WriteOutput.SentLength = make(chan int, 100)
	m.WriteOutput.Err = make(chan error, 100)
	return m
}
func (m *mockByteWriter) Write(message []byte) (sentLength int, err error) {
	m.WriteCalled <- true
	m.WriteInput.Message <- message
	return <-m.WriteOutput.SentLength, <-m.WriteOutput.Err
}
