#!/bin/bash

set -eu

bosh sync blobs

loggregator_dir=$(realpath $(dirname "$0")/..)
cf_release_dir=$(realpath $(dirname "$0")/../../../)

pushd $cf_release_dir
  ls $loggregator_dir/blobs/loggregator-blobs |
  grep -v 'lats' | grep -v 'boshhmforwarder' |
  xargs -I {} bosh add blob src/loggregator/blobs/loggregator-blobs/{} loggregator-blobs
popd
