#!/bin/bash

set -eu

function add_blob {
    local compress_output=$1
    local blob_name=$2

    shasum=$(sha1sum $compress_output)
    current_shasum=$(bosh blobs | grep $blob_name | awk '{print $5}')

    if [ "$shasum" != "$current_shasum" ]; then
        bosh add-blob $compress_output $blob_name
    fi
}

function compile_linux {
    local name=$1
    local pkg=${2:-$1}
    local build_output=$workspace/bin/$name
    local compress_output=$workspace/bin/$name.xz
    local blob_name=loggregator-blobs/$name.xz

    echo "building $name -- LINUX"
    GOOS=linux go build -o $build_output $pkg
    xz -f $build_output
    add_blob $compress_output $blob_name
}

function compile_test_linux {
    local name=$1
    local pkg=${2:-$1}
    local build_output=$workspace/bin/$name
    local compress_output=$workspace/bin/$name.xz
    local blob_name=loggregator-blobs/$name.xz

    echo "building test $name -- LINUX TEST"
    GOOS=linux go test -c -o $build_output $pkg
    xz -f $build_output
    add_blob $compress_output $blob_name
}

function compile_windows {
    local name=$1
    local pkg=${2:-$1}
    local build_output=$workspace/bin/$name.exe
    local blob_name=loggregator-blobs/$name.exe

    echo "building test $name -- WIN"
    GOOS=windows go build -o $build_output $pkg
    add_blob $build_output $blob_name
}


workspace=$(realpath $(dirname "$0")/..)
export GOPATH=$workspace

compile_linux "metron" &
compile_linux "doppler" &
compile_linux "trafficcontroller" &
compile_linux "syslog_drain_binder" &
compile_linux "statsd-injector" &
compile_linux "boshhmforwarder" &
compile_linux "deaagent" "deaagent/deaagent" &
compile_test_linux "lats" &
compile_windows "metron" &
wait
