#!/bin/bash

set -e

mkdir -p bin
for line in metron trafficcontroller doppler syslog_drain_binder; do
  echo building $line
  go build -o bin/$line $line
done

echo building lats
go test -c -o bin/lats lats
