#!/bin/bash

set -ex

env_name="${1:-lite}"

bosh create-release --force
bosh upload-release --environment="$env_name" --rebase
bosh deploy manifests/loggregator.yml \
    --ops-file=manifests/operations/no-traffic-controller.yml \
    --vars-store=/tmp/loggregator-vars.yml \
    --environment="$env_name" \
    --deployment=loggregator \
    --non-interactive
