#!/usr/bin/env bash

set -e -x

env_name=$1
if [ "$env_name" == '' ]
then
    env_name=lite
fi

bosh create-release --force
bosh -e $env_name upload-release --rebase
bosh -e $env_name deploy -n -d loggregator templates/loggregator.yml \
    --vars-store=/tmp/loggregator-vars.yml
