#!/bin/bash

set -ex

if [[ "$#" -ne 1 ]]; then
  echo "usage: $0 <protocol>"
  exit 1
fi

script_dir=$(dirname $0)
loggregator_dir=$(dirname $script_dir)
director_uuid=$(bosh status --uuid)

spiff merge $loggregator_dir/templates/loggregator-infrastructure-bosh-lite.yml \
  $loggregator_dir/templates/bosh-lite-cloud-config.yml \
  > /tmp/lite-networks.yml

printf "director_uuid: ${director_uuid}\nproperties:\nmetron_agent:\nprotocols: [\"${1}\"]\n" > /tmp/protocols.yml

spiff merge $loggregator_dir/templates/loggregator.yml \
  $loggregator_dir/templates/bosh-lite-certs.yml \
  /tmp/protocols.yml \
  /tmp/lite-networks.yml \
  > /tmp/lite-loggregator.yml

echo "Bosh lite manifest created at /tmp/lite-loggregator.yml"

bosh deployment /tmp/lite-loggregator.yml
