#!/bin/bash
set -e

trap "echo Exited!; exit 1;" SIGINT SIGTERM

base=$(dirname $0)

echo "Installing Git Hooks..."
$base/install-git-hooks

go install github.com/nats-io/gnatsd

echo "Running Tests..."
$base/ci_test $1
