#!/bin/bash -e

source /var/vcap/jobs/reverse_log_proxy_gateway_cf_auth_proxy/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 rlp-gateway-cf-auth-proxy
      killall -9 rlp-gateway-cf-auth-proxy
      killall -2 rlp-gateway-cf-auth-proxy
      killall -3 rlp-gateway-cf-auth-proxy
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./rlp-gateway-cf-auth-proxy &>> ${LOG_DIR}/rlp-gateway-cf-auth-proxy.log

    ;;

  stop)
    set +e
      killall -15 rlp-gateway-cf-auth-proxy
      killall -9 rlp-gateway-cf-auth-proxy
      killall -2 rlp-gateway-cf-auth-proxy
      killall -3 rlp-gateway-cf-auth-proxy
    set -e

    rm -f $PIDFILE

    ;;

  profile)
    exec chpst -u vcap:vcap $PROFILE_EXECUTABLE

    ;;

  *)
    echo "Usage: ctl {start|stop|profile}"

    ;;

esac
