// Code generated by protoc-gen-go.
// source: doppler_trafficcontroller.proto
// DO NOT EDIT!

/*
Package plumbing is a generated protocol buffer package.

It is generated from these files:
	doppler_trafficcontroller.proto

It has these top-level messages:
	SubscriptionRequest
	Filter
	Response
	ContainerMetricsRequest
	ContainerMetricsResponse
	RecentLogsRequest
	RecentLogsResponse
*/
package plumbing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubscriptionRequest struct {
	ShardID string  `protobuf:"bytes,1,opt,name=shardID" json:"shardID,omitempty"`
	Filter  *Filter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
}

func (m *SubscriptionRequest) Reset()                    { *m = SubscriptionRequest{} }
func (m *SubscriptionRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionRequest) ProtoMessage()               {}
func (*SubscriptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubscriptionRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Filter struct {
	AppID string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ContainerMetricsRequest struct {
	AppID string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
}

func (m *ContainerMetricsRequest) Reset()                    { *m = ContainerMetricsRequest{} }
func (m *ContainerMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerMetricsRequest) ProtoMessage()               {}
func (*ContainerMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ContainerMetricsResponse struct {
	Payload [][]byte `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ContainerMetricsResponse) Reset()                    { *m = ContainerMetricsResponse{} }
func (m *ContainerMetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerMetricsResponse) ProtoMessage()               {}
func (*ContainerMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RecentLogsRequest struct {
	AppID string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
}

func (m *RecentLogsRequest) Reset()                    { *m = RecentLogsRequest{} }
func (m *RecentLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*RecentLogsRequest) ProtoMessage()               {}
func (*RecentLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RecentLogsResponse struct {
	Payload [][]byte `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
}

func (m *RecentLogsResponse) Reset()                    { *m = RecentLogsResponse{} }
func (m *RecentLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*RecentLogsResponse) ProtoMessage()               {}
func (*RecentLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*SubscriptionRequest)(nil), "plumbing.SubscriptionRequest")
	proto.RegisterType((*Filter)(nil), "plumbing.Filter")
	proto.RegisterType((*Response)(nil), "plumbing.Response")
	proto.RegisterType((*ContainerMetricsRequest)(nil), "plumbing.ContainerMetricsRequest")
	proto.RegisterType((*ContainerMetricsResponse)(nil), "plumbing.ContainerMetricsResponse")
	proto.RegisterType((*RecentLogsRequest)(nil), "plumbing.RecentLogsRequest")
	proto.RegisterType((*RecentLogsResponse)(nil), "plumbing.RecentLogsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Doppler service

type DopplerClient interface {
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (Doppler_SubscribeClient, error)
	ContainerMetrics(ctx context.Context, in *ContainerMetricsRequest, opts ...grpc.CallOption) (*ContainerMetricsResponse, error)
	RecentLogs(ctx context.Context, in *RecentLogsRequest, opts ...grpc.CallOption) (*RecentLogsResponse, error)
}

type dopplerClient struct {
	cc *grpc.ClientConn
}

func NewDopplerClient(cc *grpc.ClientConn) DopplerClient {
	return &dopplerClient{cc}
}

func (c *dopplerClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (Doppler_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Doppler_serviceDesc.Streams[0], c.cc, "/plumbing.Doppler/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &dopplerSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Doppler_SubscribeClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type dopplerSubscribeClient struct {
	grpc.ClientStream
}

func (x *dopplerSubscribeClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dopplerClient) ContainerMetrics(ctx context.Context, in *ContainerMetricsRequest, opts ...grpc.CallOption) (*ContainerMetricsResponse, error) {
	out := new(ContainerMetricsResponse)
	err := grpc.Invoke(ctx, "/plumbing.Doppler/ContainerMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dopplerClient) RecentLogs(ctx context.Context, in *RecentLogsRequest, opts ...grpc.CallOption) (*RecentLogsResponse, error) {
	out := new(RecentLogsResponse)
	err := grpc.Invoke(ctx, "/plumbing.Doppler/RecentLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Doppler service

type DopplerServer interface {
	Subscribe(*SubscriptionRequest, Doppler_SubscribeServer) error
	ContainerMetrics(context.Context, *ContainerMetricsRequest) (*ContainerMetricsResponse, error)
	RecentLogs(context.Context, *RecentLogsRequest) (*RecentLogsResponse, error)
}

func RegisterDopplerServer(s *grpc.Server, srv DopplerServer) {
	s.RegisterService(&_Doppler_serviceDesc, srv)
}

func _Doppler_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DopplerServer).Subscribe(m, &dopplerSubscribeServer{stream})
}

type Doppler_SubscribeServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type dopplerSubscribeServer struct {
	grpc.ServerStream
}

func (x *dopplerSubscribeServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Doppler_ContainerMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DopplerServer).ContainerMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumbing.Doppler/ContainerMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DopplerServer).ContainerMetrics(ctx, req.(*ContainerMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doppler_RecentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DopplerServer).RecentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumbing.Doppler/RecentLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DopplerServer).RecentLogs(ctx, req.(*RecentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Doppler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plumbing.Doppler",
	HandlerType: (*DopplerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainerMetrics",
			Handler:    _Doppler_ContainerMetrics_Handler,
		},
		{
			MethodName: "RecentLogs",
			Handler:    _Doppler_RecentLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Doppler_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("doppler_trafficcontroller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0x75, 0x35, 0xf2, 0x31, 0x7a, 0xc0, 0xd1, 0xc4, 0x0d, 0x7e, 0x61, 0xe3, 0x01, 0x2f, 0xab,
	0x41, 0x7f, 0x81, 0x12, 0x13, 0x12, 0xbd, 0xd4, 0x93, 0xf1, 0x60, 0xba, 0xcb, 0x80, 0x4d, 0x6a,
	0x5b, 0xdb, 0x72, 0xf0, 0x87, 0x7b, 0x37, 0x02, 0x75, 0x09, 0xae, 0x72, 0x9c, 0x79, 0xaf, 0xef,
	0xcd, 0xbc, 0x29, 0x9c, 0x0c, 0x8d, 0xb5, 0x8a, 0xdc, 0x4b, 0x70, 0x62, 0x34, 0x92, 0x45, 0x61,
	0x74, 0x70, 0x46, 0x29, 0x72, 0x99, 0x75, 0x26, 0x18, 0x6c, 0x58, 0x35, 0x79, 0xcb, 0xa5, 0x1e,
	0xb3, 0x27, 0xd8, 0x7d, 0x9c, 0xe4, 0xbe, 0x70, 0xd2, 0x06, 0x69, 0x34, 0xa7, 0xf7, 0x09, 0xf9,
	0x80, 0x29, 0xd4, 0xfd, 0xab, 0x70, 0xc3, 0x41, 0x3f, 0x4d, 0x3a, 0x49, 0xb7, 0xc9, 0x63, 0x89,
	0x5d, 0xa8, 0x8d, 0xa4, 0x0a, 0xe4, 0xd2, 0xf5, 0x4e, 0xd2, 0xdd, 0xea, 0xb5, 0xb2, 0xa8, 0x95,
	0xdd, 0x4d, 0xfb, 0x7c, 0x8e, 0xb3, 0x63, 0xa8, 0xcd, 0x3a, 0xb8, 0x07, 0x9b, 0xc2, 0xda, 0x1f,
	0xad, 0x59, 0xc1, 0xce, 0xa0, 0xc1, 0xc9, 0x5b, 0xa3, 0x3d, 0x7d, 0xfb, 0x59, 0xf1, 0xa1, 0x8c,
	0x18, 0x4e, 0x39, 0xdb, 0x3c, 0x96, 0xec, 0x02, 0xf6, 0x6f, 0x8d, 0x0e, 0x42, 0x6a, 0x72, 0x0f,
	0x14, 0x9c, 0x2c, 0x7c, 0x1c, 0xb2, 0x5a, 0xf6, 0x1a, 0xd2, 0xdf, 0x0f, 0xaa, 0x6c, 0x36, 0x16,
	0x6d, 0xce, 0x61, 0x87, 0x53, 0x41, 0x3a, 0xdc, 0x9b, 0xf1, 0x0a, 0x83, 0x0c, 0x70, 0x91, 0xba,
	0x4a, 0xba, 0xf7, 0x99, 0x40, 0xbd, 0x3f, 0x3b, 0x08, 0xde, 0x40, 0x73, 0x1e, 0x77, 0x4e, 0x78,
	0x54, 0x46, 0x57, 0x71, 0x83, 0x36, 0x96, 0x70, 0x74, 0x61, 0x6b, 0x97, 0x09, 0x3e, 0x43, 0x6b,
	0x79, 0x41, 0x3c, 0x2d, 0xb9, 0x7f, 0xa4, 0xd5, 0x66, 0xff, 0x51, 0xa2, 0x3c, 0x0e, 0x00, 0xca,
	0xe5, 0xf0, 0x60, 0x71, 0x84, 0xa5, 0x74, 0xda, 0x87, 0xd5, 0x60, 0x94, 0xca, 0x6b, 0xd3, 0xbf,
	0x76, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x88, 0x3f, 0xef, 0x8e, 0x02, 0x00, 0x00,
}
