// Code generated by protoc-gen-go.
// source: grpc.proto
// DO NOT EDIT!

/*
Package plumbing is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	EnvelopeData
	PushResponse
	SubscriptionRequest
	Filter
	LogFilter
	CounterFilter
	GaugeFilter
	TimerFilter
	Response
	ContainerMetricsRequest
	ContainerMetricsResponse
	RecentLogsRequest
	RecentLogsResponse
*/
package plumbing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnvelopeData struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *EnvelopeData) Reset()                    { *m = EnvelopeData{} }
func (m *EnvelopeData) String() string            { return proto.CompactTextString(m) }
func (*EnvelopeData) ProtoMessage()               {}
func (*EnvelopeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PushResponse struct {
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SubscriptionRequest struct {
	ShardID string  `protobuf:"bytes,1,opt,name=shardID" json:"shardID,omitempty"`
	Filter  *Filter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
}

func (m *SubscriptionRequest) Reset()                    { *m = SubscriptionRequest{} }
func (m *SubscriptionRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionRequest) ProtoMessage()               {}
func (*SubscriptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubscriptionRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Filter struct {
	AppID string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Filter_Log
	//	*Filter_Counter
	//	*Filter_Gauge
	//	*Filter_Timer
	Message isFilter_Message `protobuf_oneof:"Message"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isFilter_Message interface {
	isFilter_Message()
}

type Filter_Log struct {
	Log *LogFilter `protobuf:"bytes,2,opt,name=log,oneof"`
}
type Filter_Counter struct {
	Counter *CounterFilter `protobuf:"bytes,3,opt,name=counter,oneof"`
}
type Filter_Gauge struct {
	Gauge *GaugeFilter `protobuf:"bytes,4,opt,name=gauge,oneof"`
}
type Filter_Timer struct {
	Timer *TimerFilter `protobuf:"bytes,5,opt,name=timer,oneof"`
}

func (*Filter_Log) isFilter_Message()     {}
func (*Filter_Counter) isFilter_Message() {}
func (*Filter_Gauge) isFilter_Message()   {}
func (*Filter_Timer) isFilter_Message()   {}

func (m *Filter) GetMessage() isFilter_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Filter) GetLog() *LogFilter {
	if x, ok := m.GetMessage().(*Filter_Log); ok {
		return x.Log
	}
	return nil
}

func (m *Filter) GetCounter() *CounterFilter {
	if x, ok := m.GetMessage().(*Filter_Counter); ok {
		return x.Counter
	}
	return nil
}

func (m *Filter) GetGauge() *GaugeFilter {
	if x, ok := m.GetMessage().(*Filter_Gauge); ok {
		return x.Gauge
	}
	return nil
}

func (m *Filter) GetTimer() *TimerFilter {
	if x, ok := m.GetMessage().(*Filter_Timer); ok {
		return x.Timer
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Filter) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Filter_OneofMarshaler, _Filter_OneofUnmarshaler, _Filter_OneofSizer, []interface{}{
		(*Filter_Log)(nil),
		(*Filter_Counter)(nil),
		(*Filter_Gauge)(nil),
		(*Filter_Timer)(nil),
	}
}

func _Filter_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Filter)
	// Message
	switch x := m.Message.(type) {
	case *Filter_Log:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Log); err != nil {
			return err
		}
	case *Filter_Counter:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Counter); err != nil {
			return err
		}
	case *Filter_Gauge:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Gauge); err != nil {
			return err
		}
	case *Filter_Timer:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Timer); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Filter.Message has unexpected type %T", x)
	}
	return nil
}

func _Filter_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Filter)
	switch tag {
	case 2: // Message.log
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LogFilter)
		err := b.DecodeMessage(msg)
		m.Message = &Filter_Log{msg}
		return true, err
	case 3: // Message.counter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CounterFilter)
		err := b.DecodeMessage(msg)
		m.Message = &Filter_Counter{msg}
		return true, err
	case 4: // Message.gauge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GaugeFilter)
		err := b.DecodeMessage(msg)
		m.Message = &Filter_Gauge{msg}
		return true, err
	case 5: // Message.timer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TimerFilter)
		err := b.DecodeMessage(msg)
		m.Message = &Filter_Timer{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Filter_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Filter)
	// Message
	switch x := m.Message.(type) {
	case *Filter_Log:
		s := proto.Size(x.Log)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Filter_Counter:
		s := proto.Size(x.Counter)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Filter_Gauge:
		s := proto.Size(x.Gauge)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Filter_Timer:
		s := proto.Size(x.Timer)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LogFilter struct {
}

func (m *LogFilter) Reset()                    { *m = LogFilter{} }
func (m *LogFilter) String() string            { return proto.CompactTextString(m) }
func (*LogFilter) ProtoMessage()               {}
func (*LogFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CounterFilter struct {
}

func (m *CounterFilter) Reset()                    { *m = CounterFilter{} }
func (m *CounterFilter) String() string            { return proto.CompactTextString(m) }
func (*CounterFilter) ProtoMessage()               {}
func (*CounterFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GaugeFilter struct {
}

func (m *GaugeFilter) Reset()                    { *m = GaugeFilter{} }
func (m *GaugeFilter) String() string            { return proto.CompactTextString(m) }
func (*GaugeFilter) ProtoMessage()               {}
func (*GaugeFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type TimerFilter struct {
}

func (m *TimerFilter) Reset()                    { *m = TimerFilter{} }
func (m *TimerFilter) String() string            { return proto.CompactTextString(m) }
func (*TimerFilter) ProtoMessage()               {}
func (*TimerFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Note: Ideally this would be EnvelopeData but for the time being we do not
// want to pay the cost of planning an upgrade path for this to be renamed.
type Response struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ContainerMetricsRequest struct {
	AppID string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
}

func (m *ContainerMetricsRequest) Reset()                    { *m = ContainerMetricsRequest{} }
func (m *ContainerMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerMetricsRequest) ProtoMessage()               {}
func (*ContainerMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ContainerMetricsResponse struct {
	Payload [][]byte `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ContainerMetricsResponse) Reset()                    { *m = ContainerMetricsResponse{} }
func (m *ContainerMetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerMetricsResponse) ProtoMessage()               {}
func (*ContainerMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RecentLogsRequest struct {
	AppID string `protobuf:"bytes,1,opt,name=appID" json:"appID,omitempty"`
}

func (m *RecentLogsRequest) Reset()                    { *m = RecentLogsRequest{} }
func (m *RecentLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*RecentLogsRequest) ProtoMessage()               {}
func (*RecentLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type RecentLogsResponse struct {
	Payload [][]byte `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
}

func (m *RecentLogsResponse) Reset()                    { *m = RecentLogsResponse{} }
func (m *RecentLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*RecentLogsResponse) ProtoMessage()               {}
func (*RecentLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*EnvelopeData)(nil), "plumbing.EnvelopeData")
	proto.RegisterType((*PushResponse)(nil), "plumbing.PushResponse")
	proto.RegisterType((*SubscriptionRequest)(nil), "plumbing.SubscriptionRequest")
	proto.RegisterType((*Filter)(nil), "plumbing.Filter")
	proto.RegisterType((*LogFilter)(nil), "plumbing.LogFilter")
	proto.RegisterType((*CounterFilter)(nil), "plumbing.CounterFilter")
	proto.RegisterType((*GaugeFilter)(nil), "plumbing.GaugeFilter")
	proto.RegisterType((*TimerFilter)(nil), "plumbing.TimerFilter")
	proto.RegisterType((*Response)(nil), "plumbing.Response")
	proto.RegisterType((*ContainerMetricsRequest)(nil), "plumbing.ContainerMetricsRequest")
	proto.RegisterType((*ContainerMetricsResponse)(nil), "plumbing.ContainerMetricsResponse")
	proto.RegisterType((*RecentLogsRequest)(nil), "plumbing.RecentLogsRequest")
	proto.RegisterType((*RecentLogsResponse)(nil), "plumbing.RecentLogsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Doppler service

type DopplerClient interface {
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (Doppler_SubscribeClient, error)
	ContainerMetrics(ctx context.Context, in *ContainerMetricsRequest, opts ...grpc.CallOption) (*ContainerMetricsResponse, error)
	RecentLogs(ctx context.Context, in *RecentLogsRequest, opts ...grpc.CallOption) (*RecentLogsResponse, error)
}

type dopplerClient struct {
	cc *grpc.ClientConn
}

func NewDopplerClient(cc *grpc.ClientConn) DopplerClient {
	return &dopplerClient{cc}
}

func (c *dopplerClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (Doppler_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Doppler_serviceDesc.Streams[0], c.cc, "/plumbing.Doppler/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &dopplerSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Doppler_SubscribeClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type dopplerSubscribeClient struct {
	grpc.ClientStream
}

func (x *dopplerSubscribeClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dopplerClient) ContainerMetrics(ctx context.Context, in *ContainerMetricsRequest, opts ...grpc.CallOption) (*ContainerMetricsResponse, error) {
	out := new(ContainerMetricsResponse)
	err := grpc.Invoke(ctx, "/plumbing.Doppler/ContainerMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dopplerClient) RecentLogs(ctx context.Context, in *RecentLogsRequest, opts ...grpc.CallOption) (*RecentLogsResponse, error) {
	out := new(RecentLogsResponse)
	err := grpc.Invoke(ctx, "/plumbing.Doppler/RecentLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Doppler service

type DopplerServer interface {
	Subscribe(*SubscriptionRequest, Doppler_SubscribeServer) error
	ContainerMetrics(context.Context, *ContainerMetricsRequest) (*ContainerMetricsResponse, error)
	RecentLogs(context.Context, *RecentLogsRequest) (*RecentLogsResponse, error)
}

func RegisterDopplerServer(s *grpc.Server, srv DopplerServer) {
	s.RegisterService(&_Doppler_serviceDesc, srv)
}

func _Doppler_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DopplerServer).Subscribe(m, &dopplerSubscribeServer{stream})
}

type Doppler_SubscribeServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type dopplerSubscribeServer struct {
	grpc.ServerStream
}

func (x *dopplerSubscribeServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Doppler_ContainerMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DopplerServer).ContainerMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumbing.Doppler/ContainerMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DopplerServer).ContainerMetrics(ctx, req.(*ContainerMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doppler_RecentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DopplerServer).RecentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumbing.Doppler/RecentLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DopplerServer).RecentLogs(ctx, req.(*RecentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Doppler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plumbing.Doppler",
	HandlerType: (*DopplerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainerMetrics",
			Handler:    _Doppler_ContainerMetrics_Handler,
		},
		{
			MethodName: "RecentLogs",
			Handler:    _Doppler_RecentLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Doppler_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

// Client API for DopplerIngestor service

type DopplerIngestorClient interface {
	Pusher(ctx context.Context, opts ...grpc.CallOption) (DopplerIngestor_PusherClient, error)
}

type dopplerIngestorClient struct {
	cc *grpc.ClientConn
}

func NewDopplerIngestorClient(cc *grpc.ClientConn) DopplerIngestorClient {
	return &dopplerIngestorClient{cc}
}

func (c *dopplerIngestorClient) Pusher(ctx context.Context, opts ...grpc.CallOption) (DopplerIngestor_PusherClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DopplerIngestor_serviceDesc.Streams[0], c.cc, "/plumbing.DopplerIngestor/Pusher", opts...)
	if err != nil {
		return nil, err
	}
	x := &dopplerIngestorPusherClient{stream}
	return x, nil
}

type DopplerIngestor_PusherClient interface {
	Send(*EnvelopeData) error
	CloseAndRecv() (*PushResponse, error)
	grpc.ClientStream
}

type dopplerIngestorPusherClient struct {
	grpc.ClientStream
}

func (x *dopplerIngestorPusherClient) Send(m *EnvelopeData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dopplerIngestorPusherClient) CloseAndRecv() (*PushResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PushResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DopplerIngestor service

type DopplerIngestorServer interface {
	Pusher(DopplerIngestor_PusherServer) error
}

func RegisterDopplerIngestorServer(s *grpc.Server, srv DopplerIngestorServer) {
	s.RegisterService(&_DopplerIngestor_serviceDesc, srv)
}

func _DopplerIngestor_Pusher_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DopplerIngestorServer).Pusher(&dopplerIngestorPusherServer{stream})
}

type DopplerIngestor_PusherServer interface {
	SendAndClose(*PushResponse) error
	Recv() (*EnvelopeData, error)
	grpc.ServerStream
}

type dopplerIngestorPusherServer struct {
	grpc.ServerStream
}

func (x *dopplerIngestorPusherServer) SendAndClose(m *PushResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dopplerIngestorPusherServer) Recv() (*EnvelopeData, error) {
	m := new(EnvelopeData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DopplerIngestor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plumbing.DopplerIngestor",
	HandlerType: (*DopplerIngestorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pusher",
			Handler:       _DopplerIngestor_Pusher_Handler,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x8e, 0x09, 0x49, 0x9a, 0x49, 0x4a, 0xcb, 0x14, 0xa8, 0x15, 0x40, 0x2a, 0x2b, 0x24, 0xcc,
	0x81, 0x80, 0x52, 0x8e, 0x9c, 0xda, 0xf0, 0x88, 0xd4, 0x0a, 0x64, 0xb8, 0x20, 0x4e, 0x1b, 0x77,
	0xd8, 0x5a, 0x72, 0x77, 0x97, 0xdd, 0x35, 0x12, 0x3f, 0x98, 0x9f, 0xc0, 0x1d, 0xf9, 0xed, 0xa6,
	0x56, 0x73, 0x9c, 0x99, 0xef, 0xfb, 0xe6, 0x0d, 0x20, 0x8c, 0x8e, 0xe6, 0xda, 0x28, 0xa7, 0x70,
	0x47, 0x27, 0xe9, 0xd5, 0x3a, 0x96, 0x82, 0x05, 0x30, 0x7d, 0x2f, 0x7f, 0x53, 0xa2, 0x34, 0x2d,
	0xb9, 0xe3, 0xe8, 0xc3, 0x48, 0xf3, 0x3f, 0x89, 0xe2, 0x17, 0xbe, 0x77, 0xe4, 0x05, 0xd3, 0xb0,
	0x32, 0xd9, 0x3d, 0x98, 0x7e, 0x49, 0xed, 0x65, 0x48, 0x56, 0x2b, 0x69, 0x89, 0x7d, 0x87, 0x83,
	0xaf, 0xe9, 0xda, 0x46, 0x26, 0xd6, 0x2e, 0x56, 0x32, 0xa4, 0x5f, 0x29, 0x59, 0x97, 0x09, 0xd8,
	0x4b, 0x6e, 0x2e, 0x56, 0xcb, 0x5c, 0x60, 0x1c, 0x56, 0x26, 0x06, 0x30, 0xfc, 0x19, 0x27, 0x8e,
	0x8c, 0x7f, 0xe7, 0xc8, 0x0b, 0x26, 0x8b, 0xfd, 0x79, 0x55, 0xc5, 0xfc, 0x43, 0xee, 0x0f, 0xcb,
	0x38, 0xfb, 0xeb, 0xc1, 0xb0, 0x70, 0xe1, 0x03, 0x18, 0x70, 0xad, 0x6b, 0xb1, 0xc2, 0xc0, 0x17,
	0xd0, 0x4f, 0x94, 0x28, 0x75, 0x0e, 0x1a, 0x9d, 0x33, 0x25, 0x0a, 0xde, 0xa7, 0x5e, 0x98, 0x21,
	0xf0, 0x18, 0x46, 0x91, 0x4a, 0x65, 0x96, 0xb4, 0x9f, 0x83, 0x0f, 0x1b, 0xf0, 0x69, 0x11, 0xa8,
	0x09, 0x15, 0x12, 0x5f, 0xc1, 0x40, 0xf0, 0x54, 0x90, 0x7f, 0x37, 0xa7, 0x3c, 0x6c, 0x28, 0x1f,
	0x33, 0x77, 0x4d, 0x28, 0x50, 0x19, 0xdc, 0xc5, 0x57, 0x64, 0xfc, 0xc1, 0x26, 0xfc, 0x5b, 0xe6,
	0x6e, 0xe0, 0x39, 0xea, 0x64, 0x0c, 0xa3, 0x73, 0xb2, 0x96, 0x0b, 0x62, 0x13, 0x18, 0xd7, 0x15,
	0xb3, 0x3d, 0xd8, 0xbd, 0x56, 0x11, 0xdb, 0x85, 0x49, 0x2b, 0x5f, 0x66, 0xb6, 0xf4, 0xd8, 0x73,
	0xd8, 0xa9, 0x56, 0x71, 0xcb, 0xd2, 0x5e, 0xc3, 0xe1, 0xa9, 0x92, 0x8e, 0xc7, 0x92, 0xcc, 0x39,
	0x39, 0x13, 0x47, 0xb6, 0x5a, 0x54, 0xe7, 0x64, 0xd9, 0x5b, 0xf0, 0x6f, 0x12, 0xba, 0xd2, 0xf4,
	0xdb, 0x69, 0x5e, 0xc2, 0xfd, 0x90, 0x22, 0x92, 0xee, 0x4c, 0x89, 0x2d, 0x09, 0xe6, 0x80, 0x6d,
	0xe8, 0x36, 0xe9, 0xc5, 0x3f, 0x0f, 0x46, 0x4b, 0xa5, 0x75, 0x42, 0x06, 0x4f, 0x60, 0x5c, 0x9e,
	0xdc, 0x9a, 0xf0, 0x69, 0x33, 0xe7, 0x8e, 0x3b, 0x9c, 0x61, 0x13, 0xae, 0x4f, 0xb6, 0xf7, 0xc6,
	0xc3, 0x1f, 0xb0, 0xbf, 0xd9, 0x20, 0x3e, 0x6b, 0x1f, 0x45, 0xe7, 0xb4, 0x66, 0xec, 0x36, 0x48,
	0x25, 0x8f, 0x2b, 0x80, 0xa6, 0x39, 0x7c, 0xdc, 0x2e, 0x61, 0x63, 0x3a, 0xb3, 0x27, 0xdd, 0xc1,
	0x4a, 0x6a, 0xf1, 0x19, 0xf6, 0xca, 0xb6, 0x57, 0x52, 0x90, 0x75, 0xca, 0xe0, 0x3b, 0x18, 0x66,
	0x1f, 0x48, 0x06, 0x1f, 0x35, 0xe4, 0xf6, 0xf7, 0xce, 0x5a, 0xfe, 0x6b, 0xbf, 0xda, 0x0b, 0xbc,
	0xf5, 0x30, 0x7f, 0xfd, 0xe3, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0xce, 0x6f, 0x98, 0x08,
	0x04, 0x00, 0x00,
}
