name: Go

on:
  push:
    branches:
    - v106.x
  pull_request:
    branches:
    - v106.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - run: go run github.com/onsi/ginkgo/ginkgo -r -race -randomizeAllSpecs -randomizeSuites -keepGoing
        working-directory: src

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - run: go vet ./...
        working-directory: src

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - uses: golangci/golangci-lint-action@v3.7.1
        with:
          args: --config .golangci.yml
          working-directory: src
